### ISSUE TITLE
remove linkouts from record page headers

### ISSUE THREAD

**Issue by fossilfriend** [NIAGADS/GenomicsDBWebsite#10]
add to curation, annotation sections

**Comment by cklamann** [comment]
- linkouts have been removed from gene record page headers and should be displaying as of this commit: e77cdb801ad8ccf4c90ddab48395894a82d1cfb9 and other record pages have been prepared to have links moved to body

**Comment by cklamann** [comment]
- removed unused linkout code from gene header view here: e21f1e8cad2de6165b0e70adae573bd5c6066b77
