### ISSUE TITLE
router links in search result table are relative instead of absolute

### ISSUE THREAD

**Issue by fossilfriend** [NIAGADS/GenomicsDBWebsite#12]
as an example, run a gwas_stats search and click on an impacted gene in the search result

**Comment by cklamann** [comment]
- here's an example link: `msc_impacted_gene_link: "{"url": "../gene/ENSG00000130202", "type": "link", "value": "PVRL2", "tooltip": "view gene annotations"}"` -- i think removing the leading `..` should fix things.

**Comment by cklamann** [comment]
this is a test

**Comment by fossilfriend** [comment]
actually had to code the url as `/record/gene/` fixed in model & had to update the `msc_impacted_gene` virtual column (svn commit)
