### ISSUE TITLE
Genome View: change onClick or tooltip behavior to load linkage plot

### ISSUE THREAD

**Issue by fossilfriend** [NIAGADS/GenomicsDBWebsite#15]
* related to #14 

* onClick (or tooltip) for ideogram should draw linkage plots

* write rest endpoint to return a list of variants (defining the x/y axis of the correlation matrix) and a list of triple (variant1, variant2, r2)

* use d3.js to render the linkage plot

**Comment by fossilfriend** [comment]
service implemented; endpoint takes two parameters

http://localhost:8081/genomics/service/variant/linkage?population=EUR&variants=19:45389596:G:A_rs7254892,19:45392254:C:T_rs6857,19:45415640:G:A_rs445925,19:45422946:A:G_rs4420638

**Comment by cklamann** [comment]
- created the plot here: 975a36bbfc042536b6819eb33178275d909831e4; will need some tuning once we're ready for end-to-end testing

**Comment by fossilfriend** [comment]
order variants by position on genome from upstream to downstream
use record primary key to get position

draw horizontal bar to indicate relative position of each variant in the linkage matrix in the locus; label as in https://www.broadinstitute.org/haploview/browsing-linkage-disequilibrium

**Comment by fossilfriend** [comment]
* mouseover single features: feature display name linked to record page
* mouseover spans: span display name, number of features

* linkage plots modal:
  * modal title: Linkage
  * rename Correlation components to Linkage 
  * (possibly) do color scale according to bins from 0 - 1 as in locus zoom (but still using shades of red w/white == 0 - 0.2)
  * put the span (display_id) for the clicked triangle in the modal and/or modal title
 * indicate relative position of the variants on reference line

**Comment by fossilfriend** [comment]
example call w/a lot of variants

https://beta.niagads.org:8443/genomicsqa/service/variant/linkage?population=EUR&variants=19:45048120:G:T_rs1727747,19:45048323:C:T_rs1727748,19:45048379:T:C_rs1661176,19:45048629:G:A_rs1661175,19:45049103:G:A_rs1727751,19:45050138:C:T_rs8111044,19:45050490:A:C_rs1626475,19:45074177:G:T_rs846848,19:45165912:C:A_rs714948,19:45202027:G:A_rs12150984,19:45202052:C:T_rs2965164,19:45205877:T:C_rs8108277,19:45225345:C:T_rs2965109,19:45227742:T:C_rs7254776,19:45231478:G:A_rs2927488,19:45237812:T:C_rs2965101,19:45240371:C:T_rs17728272,19:45242107:A:G_rs2927438,19:45242173:G:A_rs1531517,19:45247627:A:G_rs4803750,19:45253104:T:A_rs8100239,19:45254168:C:A_rs8103315,19:45313715:T:C_rs2927477,19:45326768:C:T_rs1871045,19:45327459:T:C_rs4803759,19:45329214:T:G_rs10402271,19:45333834:T:C_rs4803760,19:45336035:T:C_rs7359852,19:45337385:G:C_rs2927480,19:45338493:T:C_rs4605275,19:45344458:A:G_rs2972564,19:45351746:A:G_rs1871047,19:45351937:T:C_rs1871046,19:45357291:G:C_rs4803763,19:45361224:G:A_rs440277,19:45362667:G:A_rs377702,19:45363700:A:G_rs12978931,19:45366779:T:C_rs519825,19:45367777:C:T_rs8105340,19:45370838:G:A_rs12610605,19:45370854:G:A_rs416041,19:45379060:A:C_rs387976,19:45382034:A:G_rs6859,19:45383037:A:T_rs11673139,19:45383061:G:T_rs3852861,19:45385759:G:C_rs3745150,19:45389596:G:A_rs7254892,19:45392254:C:T_rs6857,19:45395266:G:A_rs157580,19:45395619:A:G_rs2075650,19:45396219:C:T_rs157582,19:45401666:A:G_rs8106922,19:45404691:A:G_rs405697,19:45406673:G:A_rs10119,19:45408836:T:G_rs405509,19:45414451:T:C_rs439401,19:45422946:A:G_rs4420638,19:45448465:T:G_rs5167,19:45476657:C:G_rs2293755,19:45477381:G:A_rs16979595,19:45483438:A:C_rs8111069,19:45487420:A:C_rs16979600,19:45490428:G:A_rs7257610,19:45490570:A:G_rs3786505,19:45493061:T:C_rs909134,19:45536036:C:G_rs10424046,19:45543787:C:T_rs1560725,19:45585706:T:C_rs7250924,19:45589595:C:T_rs1469704,19:45590988:G:A_rs2060250,19:45631816:G:A_rs17643262,19:45634682:G:C_rs10408847,19:45636201:C:T_rs1114832,19:45636319:C:A_rs1114831,19:45640124:A:G_rs10425074,19:45643890:T:C_rs2041262,19:45650386:C:T_rs1048699,19:45652079:T:C_rs1005451,19:45657486:C:T_rs10421247,19:45660136:A:C_rs10416371,19:45677315:T:C_rs12460041,19:45707830:A:C_rs606757,19:45707917:T:G_rs582747,19:45708239:A:G_rs605003,19:45708758:A:G_rs2627641,19:45708888:T:C_rs597668,19:45710276:A:G_rs7249082,19:45711598:C:T_rs10415983,19:45756753:A:G_rs12981533,19:45768946:T:C_rs2377324,19:45962799:A:G_rs10415949

**Comment by cklamann** [comment]
- tooltip behavior updated: e8ad5e7883623b57b2a1c7edff0cd241ccdb4a8f

**Comment by cklamann** [comment]
- relative positions indicated 8340331d40b2541e91789164370bf65513c7211f

**Comment by cklamann** [comment]
- show modal with record page links for carets with 2-4 variants: edb312ef0a8fe08425563ef4f9541783c722f8db

**Comment by cklamann** [comment]
- variant labels converted to record page links: b98980f34ad99549daf78307b99a6fcf34e0187c
