### ISSUE TITLE
add validation to inline search on gwas dataset record pages

### ISSUE THREAD

**Issue by fossilfriend** [NIAGADS/GenomicsDBWebsite#20]
`pvalue` parameter cannot have a null value/be empty but the front end kind of fails `silently`, at least for the user.  Need to add validation check that the field is not empty and probably should also add one so that it matches any of the following formats:

> 0.0007
> 3e-6
> 3^-6
> 3 x 10^-6

Note: the query will account for spaces between the `e`, `^`, `x` and numbers so don't worry about those

Ex target page: record/gwas_summary/NG00036_STAGE1

**Comment by cklamann** [comment]
- regex, validation, and error message created in ab33e83
