### ISSUE TITLE
replace table with message when no variants meet the p-value filter cutoff (gene record tables)

### ISSUE THREAD

**Issue by fossilfriend** [NIAGADS/GenomicsDBWebsite#24]
eg. https://beta.niagads.org/genomics/app/record/gene/CR1 - AD related neuropathologies and biomarkers table

**Comment by fossilfriend** [comment]
Looks good but the message needs to be corrected -- the default p-value is 5e-8, not 8.  I would correct the message to the following:

> No variants meet the default p-value cutoff for genome-wide significance (&le; 5e-8). Please adjust the p-value limit with the p-value filter.

I didn't expect github markdown to correct the html code: `&le;` for the less than/equal to sign (&le;)

**Comment by cklamann** [comment]
oddly the filter doesn't seem to be rendering anymore locally or on the beta site? 
i'm expecting the table payload to include table.properties.[type][0]["chart_filter"] but i am seeing "default" for type[0] instead, at least for the "other_variants_from_catalog" table. has the payload changed or am i looking in the wrong place?

**Comment by fossilfriend** [comment]
the  `*_variants_from_catalog` table reports 3rd party curated data that is already p-value filtered so, it is just set to be a default table

look at the tables under the `NIAGADS GWAS` section
