### ISSUE TITLE
investigate extent of broad hosted files for igv use

### ISSUE THREAD

**Issue by fossilfriend** [NIAGADS/GenomicsDBWebsite#32]
what's available for hg19/how to access 1000 genomes for hg19

are Ensembl genes available?

**Comment by fossilfriend** [comment]
it looks like 1000 genomes is hosted in a public aws bucket (independent of broad):

https://docs.opendata.aws/1000genomes/readme.html
http://s3.amazonaws.com/1000genomes

and the files can be accessed using the same directory structure we expect from the ftp site:, eg.

https://s3.amazonaws.com/1000genomes/release/20130502/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz

igv has a bunch of hosted tracks in additions to the genome in an amazon bucket: 

https://s3.amazonaws.com/igv.broadinstitute.org/

trying to find the contents

but even if we can't find their bucket contents & or access it whenever we want; this is one possible solution (remote store by creating a bucket)

**Comment by cklamann** [comment]
igv also has some annotations and genomes here: https://s3.dualstack.us-east-1.amazonaws.com/igv.org.genomes/

igv has a sample webapp on github that implements the browser -- it includes a number of sample track configs with links to live hosted tracks: https://github.com/igvteam/igv-webapp/tree/master/resources/tracks
