### ISSUE TITLE
remove colocated variant counts and any dependencies from the gene record display

### ISSUE THREAD

**Issue by fossilfriend** [NIAGADS/GenomicsDBWebsite#44]
These two attributes have been removed from the gene model: 
* num_colocated_variants
* num_unique_colocated_variants

I don't believe we are currently using them, but there are references to them in the typescript and a dependent component (which does not appear to be being used) that can be removed.

**Comment by cklamann** [comment]
I see that these are being referenced in gene record pages in the section summaries for sections with the categoryId `category:genetic_variation`. Has this category been removed from the gene record/page? If so I can remove related components from the app as well.
