### ISSUE TITLE
Site Search

### ISSUE THREAD

**Issue by fossilfriend** [NIAGADS/GenomicsDBWebsite#5]
Continue to develop site search
- refine user experience when typing search (incl. deleting, mouseover, etc)
- revise positioning/size of menu search box
- what happens in mobile view?
- use full fledge postgres text search

**Comment by cklamann** [comment]
- fixed the bug that was causing problems on rapid backspacing in 7a3f0b0c5853f0d04446e83de266fb427284fb15
- first pass at an expanding header search box here in 9041164b5f4180850715db559c5ba4a4c82adc51
