### ISSUE TITLE
customize question pages

### ISSUE THREAD

**Issue by fossilfriend** [NIAGADS/GenomicsDBWebsite#7]
- remove the "generate webservice" link
- add section that lists the datasets underlying the question
-- requires new webservice to query database for datasets linked to the question

**Comment by fossilfriend** [comment]
service to query for the datasets linked to a record attribute or question added.

service/dataset/reference?record_type=variant&target_type=question&target_name=gwas_stats

**Comment by cklamann** [comment]
- i wrapped the WDK component in our fork in ad19cfe79df5258d95e7db72f7cd1ad2fedac275
- removed the link in 3c79826d94ab79e8469c56dda827dcfea98a0c21

**Comment by cklamann** [comment]
- updated button styling in 35198ac

**Comment by cklamann** [comment]
- added basic 'datasets used' section in 2b0e07bf39cec3a1663eebc70fcf5e97e3c65282

**Comment by cklamann** [comment]
- made search page title dynamic in 9c6c870
