### ISSUE TITLE
remove "extend your search strategy" button from strategy pane

### ISSUE THREAD

**Issue by fossilfriend** [NIAGADS/GenomicsDBWebsite#9]
as first step to customize the strategies, remove the button that let's you add a step/extend the strategy

![screenshot-beta niagads org-2020 01 16-12_24_46](https://user-images.githubusercontent.com/3707878/72547924-a46ce200-385b-11ea-8470-d3942c031e16.png)

**Comment by cklamann** [comment]
- removed this button in NIAGADS/WDKClient bc95596348609dec61c1eef8defb9ad952039226 (develop branch)

**Comment by fossilfriend** [comment]
looks good; but I just found one more element that has to be removed to completely remove the ability to add strategy steps.

when you edit/revise a strategy, **'Delete'** and **'Insert step before'** should be removed from the pop-up window menu 

![screenshot-localhost_8081-2020 01 23-14_32_34](https://user-images.githubusercontent.com/3707878/73017204-5de42e00-3ded-11ea-81e3-cbc2de913166.png)

**Comment by cklamann** [comment]
- fixed the popup in the fork here: b82008a660abf81a7c6e6829dd6145555a107d27
